### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by soroka-ihor** [soroka-ihor/homepage#6]
Скласти інтро (_вступ_), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ihor-soroka** [comment]
**Hideo Kojima is the James Cameron of video games – a maverick auteur with very big ideas, a fetishistic love of technology and a constant need to push his chosen medium as far as it can possibly go, whatever the cost. Add to this an obsession with movies and the band New Order, and you have one of the most unique video game creators currently working today.**
