### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by soroka-ihor** [soroka-ihor/homepage#8]
Скласти список всіх *(важливих)* життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про *"лишні"* події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів *"паттерн"* і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ihor-soroka** [comment]
# Childhood & Early Life

* Hideo Kojima was born in Tokyo, Japan in 1963, but his family moved to western Japan shortly after his birth. Growing up as a latchkey kid, he had to deal with loneliness and loss as a child, when his father passed away while he was just 13 years old.
* From an early age, he knew that he wanted to be a writer and illustrator, but faced a lot of pressure to seek out a safer and financially stable line of work. Despite discouragement from his family and peers, as a teen, he wrote and illustrated original short stories and sent them to magazines, although none ever got published.
* While attending college and studying economics, Kojima spent a lot of his free time playing video games, which at the time was a new medium that hadn't been explored much.
* He shocked his peers by announcing in his fourth year of college that he wanted to design video games, even though his previous ambition had been to become a film director. Even though most of his friends discouraged him from pouring his energy into an untested creative outlet, he cites unwavering support from his mother as a big influence in his decision to pursue video games.
![hideo-kojima-22194](https://user-images.githubusercontent.com/64700402/80871716-86b27400-8cb6-11ea-9d57-6521bbd6c69c.jpg)

# Career

* Kojima's early career was marked by a lot of rejection, and his video game ideas failed to gain any traction with publishers. In 1986 he was hired by the game publisher ‘Konami Digital Entertainment’ to work in their MSX home computer division as a designer and planner.
* Owing to the system's limited color palette and resources, the assignment was a bit of a disappointment to the creative and imaginative Kojima, who had hoped to work on the more colorful Nintendo system.
* Many of Kojima's early ideas were refused, but he got his big breakthrough when he was asked to take over a project called ‘Metal Gear’. He fixed problems with the game's clunky combat system by instead focusing the game play on sneaking and subterfuge.
* Released in 1987, the first ‘Metal Gear’ game introduced its tough protagonist ‘Solid Snake’ to the world, and the title remains one of Kojima's most recognizable and successful franchises.
* During the '90s Kojima's career finally took off and he began developing his own projects for the ‘Konami MSX2’ as well as for other gaming systems, including a sequel to his breakout hit ‘Metal Gear’.
* In 1998, the release of his PlayStation title ‘Metal Gear Solid’ brought him to the attention of industry insiders and fans alike and he became a celebrity in the video game world.
* He kicked of the '00s with a sequel to ‘MGS’ which was one of the most highly anticipated game releases ever at the time. He repeated his success in 2001 with the release of the video game and anime franchise ‘Zone of Enders’. By the end of the decade he had come up with several other projects, including several ‘MGS’ sequels and spinoffs.
* On April 1, 2011, Kojima was promoted to Vice President of ‘Konami Digital Entertainment’. This promotion was a step up from his previous title of Vice President of ‘Konami Computer Entertainment Japan’ and gave him almost unparalleled creative control over one of the most popular game publishers in the world.

# Major Works

* Beginning with the release of the first iteration in 1986, the ‘Metal Gear’ franchise is Kojima's biggest and most recognizable contributions to the gaming world. The main character of the title, ‘Solid Snake’, has even made appearances in other video games like ‘Nintendo's Super Smash Bros Brawl’.
* Another major Kodjima's work was Death Stranding. Death Stranding, the newest video game from the developer Hideo Kojima, was introduced to the world in the summer of 2016 on a stage at the Electronic Entertainment Expo (E3), the gaming industry’s annual trade-show extravaganza. The event was what the industry calls a press conference, but this particular spectacle more closely resembled the scene in “King Kong” when the beast is displayed to the public in a Broadway theater. A live orchestra struck up a blaring John Williams-style score as the curtain lifted to reveal a sloping stage, at the very top of which stood Kojima, a slight Japanese man with swooping black hair and glasses. The floor began to light up underneath him, panes of light flying in from left and right to create a sort of light bridge, which he bounded down to shake a Sony executive’s hand. Then he stood at center stage, beaming, to deafening applause.

# Awards & Achievements

* In 2009 the entertainment website IGN named him number six in their list of top game creators of all time. That year he also received a ‘Lifetime Achievement Award’ at the ‘Game Developers Conference’.

#  Personal Life & Legacy

* Kojima is unmarried and has no children, but continues to enjoy the support of his mother. She even plays his video games, and it is believed she took an entire year to finish ‘MGS3’.

# Net Worth

* Hideo Kojima is considered to be one of the most influential game designers of all time. His net worth is currently estimated around $30 million.

# Trivia

* The famous game designer’s anagramic pseudonym is Joakim Mogren. An actor playing Joakim Mogren made an appearance in the controversial ad campaign for ‘MGS5’ as the mysterious CEO of a fictional game design company.
